# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
