# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160129_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='telefone',
            new_name='telephone',
        ),
        migrations.AlterField(
            model_name='form',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='facebookLink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='suburb',
            field=models.CharField(max_length=100),
        ),
    ]
